"""
Prompts for Porta order extraction (email + PDF).
"""

from __future__ import annotations


PORTA_SYSTEM_PROMPT = (
    "You are a strict Porta purchase-order extraction engine. "
    "Extract one order from email + PDF into the required JSON schema. "
    "Return JSON only (no markdown, no commentary). "
    "Use only German field names exactly as requested."
)


def build_user_instructions_porta(source_priority: list[str]) -> str:
    return (
        "=== TASK ===\n"
        "Extract one Porta order from email + PDF pages.\n"
        f"SOURCE TRUST PRIORITY: {', '.join(source_priority).upper()}\n"
        "When sources conflict, follow the priority above.\n"
        "\n"
        "=== REQUIRED KEYS (EXACT NAMES) ===\n"
        "Header keys:\n"
        "ticket_number, kundennummer, adressnummer, kom_nr, kom_name, "
        "liefertermin, wunschtermin, bestelldatum, lieferanschrift, tour, "
        "store_name, store_address, seller, iln, iln_anl, iln_fil, "
        "human_review_needed, reply_needed, post_case\n"
        "Item keys:\n"
        "artikelnummer, modellnummer, menge, furncloud_id\n"
        "No English aliases.\n"
        "\n"
        "=== FIELD OBJECT FORMAT ===\n"
        "Each header/item field must be an object:\n"
        '{"value":"...", "source":"pdf|email|image|derived", "confidence":0.0-1.0}\n'
        "Always include every required key, even if value is empty.\n"
        "\n"
        "=== PORTA ITEM-CODE RULES (STRICT) ===\n"
        "Apply these mappings exactly for Porta style codes:\n"
        "0) Ignore ANY PDF table 'Artikel-Nr' value (often like '4609952 / 88' or '1005141 / 88'). "
        "This is a store-internal number and must NEVER be used as artikelnummer or modellnummer. "
        "Do NOT split it, normalize it, or use it as a fallback.\n"
        "   Example (NEGATIVE): Artikel-Nr: 1005141 / 88 -> IGNORE ENTIRELY\n"
        "1) Main code pattern around 'Auf.' line:\n"
        "   Example: 'Auf. CQ 1616 TP-67430'\n"
        "   -> artikelnummer='67430'\n"
        "   -> modellnummer='CQ1616'\n"
        "   Never swap these two for the main 'Auf.' line; the CQ+digits is always modellnummer, "
        "   the TP-<digits> is always artikelnummer (strip the 'TP-' prefix).\n"
        "   WRONG: artikelnummer='CQ1616', modellnummer='67430'\n"
        "   CORRECT: artikelnummer='67430', modellnummer='CQ1616'\n"
        "2) Accessory code pattern '<PREFIX>-<NUMERIC>' where prefix starts with 0J or OJ:\n"
        "   -> modellnummer='<PREFIX>' (NO trailing dash)\n"
        "   -> artikelnummer='<NUMERIC>'\n"
        "   Examples:\n"
        "   - OJ99-14323 -> modellnummer='OJ99', artikelnummer='14323'\n"
        "   - OJ00-66017 -> modellnummer='OJ00', artikelnummer='66017'\n"
        "   - 0J00-30156 -> modellnummer='0J00', artikelnummer='30156'\n"
        "   - 0J00-15237 -> modellnummer='0J00', artikelnummer='15237'\n"
        "   Fallback for OJ/0J prefix without visible numeric suffix:\n"
        "   If token starts with OJ or 0J but no '-<NUMERIC>' is visible (or no extractable numeric article token "
        "exists in that row), keep the row and quantity, set modellnummer to the prefix token and artikelnummer empty.\n"
        "   Example: OJ99 F-Einteilung Sockel 81 -> modellnummer='OJ99', artikelnummer=''\n"
        "3) Standard hyphen split (not 'Auf.' line and not 0J/OJ accessory pattern):\n"
        "   -> modellnummer=part BEFORE hyphen\n"
        "   -> artikelnummer=part AFTER hyphen\n"
        "   Example: CQ1616XP-00943 -> modellnummer='CQ1616XP', artikelnummer='00943'\n"
        "4) Two adjacent code-like tokens in item description (not 'Auf.' line or 0J/OJ pattern):\n"
        "   If one token is 5 characters and mostly numeric (>=4 digits),\n"
        "   -> artikelnummer=that 5-char token\n"
        "   -> modellnummer=the other token\n"
        "   Example: MODELX 72216 -> modellnummer='MODELX', artikelnummer='72216'\n"
        "5) If an item block contains the phrase 'bestehend aus je:', treat it as a decomposition block.\n"
        "   IGNORE the parent item row above the phrase for item extraction.\n"
        "   Extract only explicit component sub-lines after 'bestehend aus je:'.\n"
        "   If the same component pair appears multiple times in explicit sub-lines, output it multiple times.\n"
        "   Do NOT deduplicate identical component pairs across different pages.\n"
        "   A repeated occurrence on another page is a NEW item occurrence and must be output again.\n"
        "   Repeated PDF table 'Artikel-Nr.' values do not suppress item creation.\n"
        "   NEGATIVE EXAMPLE: legal/footer lines like 'Amtsgericht ... HRB 9684' are NEVER item/component pairs.\n"
        "   If a component line contains two code pairs, choose the pair that belongs to the component occurrence.\n"
        "6) Do not keep combined token in one field when it clearly splits.\n"
        "7) Preserve leading zeros and uppercase letters exactly.\n"
        "8) Preserve O vs 0 exactly as seen (do not normalize).\n"
        "9) If no other valid code patterns or tokens exist in the item block (excluding the OJ/0J model-only fallback above), "
        "set artikelnummer.value and modellnummer.value to empty strings with source='derived' "
        "and confidence=0.0.\n"
        "\n"
        "=== PORTA ROW EXTRACTION ===\n"
        "Porta item blocks can contain a base line plus accessory lines (e.g., '1 x ... 0J00-30156').\n"
        "Create one output item per explicit code occurrence in reading order.\n"
        "Set menge from the visible quantity for that code (default to 1 when line explicitly says '1 x').\n"
        "Create items strictly in PDF reading order (Pos 1, 1.1, 1.2, ...). Do not reorder.\n"
        "Assign line_no sequentially starting at 1.\n"
        "\n"
        "=== PDF INPUT USAGE ===\n"
        "Each PDF page includes image + digital text.\n"
        "Use image for table structure and quantities.\n"
        "Use digital text to confirm/correct artikelnummer/modellnummer and OCR confusion.\n"
        "\n"
        "=== FURNCLOUD ID (ROBUST) ===\n"
        "Find furncloud_id anywhere in email or PDF (all pages, all orientations).\n"
        "Do NOT depend on one fixed phrase.\n"
        "Scan ALL pages, even image/drawing pages with no item table; furncloud may appear only there.\n"
        "Before final output, sweep each page in order: main body, then all margins/side strips.\n"
        "\n"
        "Accept these candidate forms:\n"
        "- [xxxx xxxx]\n"
        "- (xxxx xxxx)\n"
        "- xxxx xxxx (unbracketed) when clearly code-like\n"
        "- Near labels/phrases such as furncloud, furnplan, planung, plan, zeichnung, code, id, "
        "or phrases like 'Siehe Planung (...)'.\n"
        "\n"
        "Orientation/layout handling:\n"
        "- Accept candidates in normal, vertical, rotated, or side-strip text (0/90/180/270 degrees).\n"
        "- If present only in page image (not digital text), still extract from image.\n"
        "\n"
        "Validation and normalization:\n"
        "- Valid furncloud_id is exactly 8 alphanumeric characters total.\n"
        "- Ignore spaces/punctuation/linebreaks while counting 8 chars.\n"
        "- Store format must be 'XXXX XXXX' (4 chars, space, 4 chars).\n"
        "- If source is contiguous 8 chars (e.g., 'abcd1234'), normalize to 'abcd 1234'.\n"
        "- Preserve O vs 0 exactly as seen; do not normalize characters.\n"
        "\n"
        "Candidate ranking when multiple matches exist:\n"
        "1) Candidate near explicit labels/phrases (furncloud/furnplan/planung/plan/zeichnung).\n"
        "2) Bracketed or parenthesized candidate.\n"
        "3) Margin/side-strip candidate.\n"
        "4) First by page order, then reading order on page.\n"
        "\n"
        "Reject likely non-furncloud values:\n"
        "- ILN/GLN (13-digit numbers), ticket/order numbers, artikelnummer/modellnummer tokens, dates.\n"
        "- Any candidate that is not exactly 8 alphanumeric characters after cleanup.\n"
        "\n"
        "If found once, apply the same furncloud_id to all items.\n"
        "If not found, leave furncloud_id empty with low confidence.\n"
        "\n"
        "=== HEADER EXTRACTION HINTS ===\n"
        "kundennummer: Kundennr/Kunden-Nr/Debitor/Konto\n"
        "kom_nr: Auftragsnr/Bestellnr/Order/Kommission. If kom_nr ends with '/0', drop the '/0' and keep only the number.\n"
        "bestelldatum: Bestelldatum/Datum\n"
        "liefertermin or wunschtermin: Liefertermin/Wunschliefertermin\n"
        "lieferanschrift: Lieferadresse/Lieferanschrift/Empfaenger block\n"
        "ILN from Anlieferung block: If the 'Anlieferung' section contains a 13-digit ILN/GLN "
        "(often starting with 40 or 90), extract it into BOTH iln_anl and iln.\n"
        "Do NOT include that 13-digit ILN line inside lieferanschrift.\n"
        "GLN Haus / Für Haus is NOT the delivery ILN. Do NOT map GLN Haus to iln or iln_anl.\n"
        "If both GLN Haus and Anlieferung ILN appear, ALWAYS use the Anlieferung number.\n"
        "Keep iln_fil empty unless explicitly present elsewhere.\n"
        "\n"
        "\n"
        "=== ADDRESS FORMATTING (STORE + LIEFERANSCHRIFT) ===\n"
        "store_address must be exactly two lines:\n"
        "Line 1: StreetName HouseNumber,\n"
        "Line 2: PLZ City\n"
        "lieferanschrift:\n"
        "- Do NOT include company/entity/branch name lines from the delivery block.\n"
        "- Keep only delivery address lines: street line + PLZ/City line.\n"
        "If a 5-digit German postal code appears, insert a newline before it and add a comma before the newline.\n"
        "Fallback: If output ends up on a single line, still insert a comma immediately before the 5-digit PLZ.\n"
        "If the postal code is stuck to the house number (token ends with 5 digits, e.g., '204103'),\n"
        "split it into house number + postal code (e.g., '204103' -> house '2', PLZ '04103').\n"
        "Preserve characters/casing and hyphen spacing exactly as seen; only add a single comma before the newline.\n"
        "Example: 'Alte Messe 204103 Leipzig' -> 'Alte Messe 2,\\n04103 Leipzig'.\n"
        "Example (lieferanschrift): '... Bakenweg 16 - 20 32457 Porta Westfalica' "
        "-> '... Bakenweg 16 - 20,\\n32457 Porta Westfalica'.\n"
        "Example (lieferanschrift with company name present in source):\n"
        "'FuG Handelsg. Ost mbH & Co.KG Delitzscher Str. 6 06188 Sietzsch' ->\n"
        "'Delitzscher Str. 6,\\n06188 Sietzsch'.\n"
        "Example (store_address): 'Friedrich-Ebert-Str. 10133332 Guetersloh' "
        "-> 'Friedrich-Ebert-Str. 101,\\n33332 Guetersloh'.\n"
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        "Return strict JSON with top-level keys:\n"
        "message_id, received_at, header, items, status, warnings, errors\n"
        "status must be one of: ok, partial, failed.\n"
    )
