"""
Prompts for Segmuller order extraction (email + PDF).
"""

from __future__ import annotations


SEGMULLER_SYSTEM_PROMPT = (
    "You are a strict Segmuller purchase-order extraction engine. "
    "Extract one order from email + PDF into the required JSON schema. "
    "Return JSON only (no markdown, no commentary). "
    "Use only German field names exactly as requested."
)


def build_user_instructions_segmuller(source_priority: list[str]) -> str:
    return (
        "=== TASK ===\n"
        "Extract one Segmuller order from email + PDF pages.\n"
        f"SOURCE TRUST PRIORITY: {', '.join(source_priority).upper()}\n"
        "When sources conflict, follow the priority above.\n"
        "Scan all pages across all PDF attachments. Do not rely only on the first PDF.\n"
        "\n"
        "=== DOCUMENT ROLE DETECTION ===\n"
        "Classify each page before extraction:\n"
        "- Primary order pages: markers like BESTELLUNG and order table headers such as Pos/Upo/Seg-Nr./Ihre Art.-Nr.\n"
        "- Furnplan or scanned layout pages: markers like SKIZZE / AUFSTELLUNG, furnplan, rotated drawing pages, scanned layout pages.\n"
        "Furnplan/scanned pages are valid item-code sources even when digital text on those pages is sparse or empty.\n"
        "\n"
        "=== REQUIRED KEYS (EXACT NAMES) ===\n"
        "Header keys:\n"
        "ticket_number, kundennummer, adressnummer, kom_nr, kom_name, "
        "liefertermin, wunschtermin, bestelldatum, lieferanschrift, tour, "
        "store_name, store_address, seller, iln, iln_anl, iln_fil, "
        "human_review_needed, reply_needed, post_case\n"
        "Item keys:\n"
        "artikelnummer, modellnummer, menge, furncloud_id\n"
        "No English aliases.\n"
        "\n"
        "=== FIELD OBJECT FORMAT ===\n"
        "Each header/item field must be an object:\n"
        '{"value":"...", "source":"pdf|email|image|derived", "confidence":0.0-1.0}\n'
        "Always include every required key, even if value is empty.\n"
        "\n"
        "=== PDF INPUT USAGE ===\n"
        "Each PDF page includes image + digital text.\n"
        "Use the IMAGE to determine table structure, number of rows, and item quantities (menge).\n"
        "Use digital PDF text only to confirm/correct code fields and OCR ambiguities:\n"
        "- items[*].modellnummer\n"
        "- items[*].artikelnummer\n"
        "Preserve exact characters, including leading zeros and O vs 0.\n"
        "\n"
        "=== ARTICLE CODE PATTERNS ===\n"
        "- Standard hyphenated codes like 'CQ9606XA-60951' -> SPLIT on hyphen:\n"
        "    -> modellnummer = part BEFORE hyphen (e.g., 'CQ9606XA')\n"
        "    -> artikelnummer = part AFTER hyphen (e.g., '60951')\n"
        "- REVERSED hyphen pattern (CRITICAL - accessory codes):\n"
        "  - If code matches <NUMERIC>-<ALPHA> format (e.g., '56847-ZB99', '12345-AB12'):\n"
        "    -> artikelnummer = NUMERIC part (e.g., '56847')\n"
        "    -> modellnummer = ALPHA part (e.g., 'ZB99')\n"
        "  - This is the REVERSE of the standard MODEL-ARTICLE pattern!\n"
        "- Examples:\n"
        "  - 'OJ99-61469' -> artikelnummer='61469', modellnummer='OJ99' (standard)\n"
        "  - 'CQ1111XP-67538' -> artikelnummer='67538', modellnummer='CQ1111XP' (standard)\n"
        "  - '56847-ZB99' -> artikelnummer='56847', modellnummer='ZB99' (REVERSED)\n"
        "  - '12345-AB12' -> artikelnummer='12345', modellnummer='AB12' (REVERSED)\n"
        "\n"
        "=== SEGMULLER ITEM SOURCES ===\n"
        "Priority 1: Furnplan/scanned item rows (e.g. Pos | ArtNr | Beschreibung | ... | Menge).\n"
        "Priority 2: Order-table rows only if Furnplan codes are missing or unreadable.\n"
        "- Article codes from Furnplan rows -> same split rules as above\n"
        "- menge <- Menge column\n"
        "- Use Beschreibung token fallback only when ArtNr is missing/unreadable.\n"
        "From order-table fallback rows: use only as fallback; prefer richer code fields from Furnplan.\n"
        "If order table and Furnplan describe the same real item (same Seg-Nr or same item context), output one merged line and keep Furnplan code fields.\n"
        "\n"
        "### PDF/TIF Attachment (furnplan style):\n"
        "- Article codes -> same split rules as above\n"
        "- 'Menge' or quantity column -> menge\n"
        "- '[xxxx xxxx]' bracket codes (may be sideways/rotated) -> furncloud_id\n"
        "- Extract ALL items from ALL pages - don't stop after first table!\n"
        "\n"
        "=== ROW EXTRACTION ===\n"
        "Create one output item per explicit order row in reading order.\n"
        "Assign line_no sequentially starting at 1.\n"
        "Do not reorder rows.\n"
        "\n"
        "=== SEGMULLER FURNCLOUD_ID ===\n"
        "Find furncloud_id anywhere in email or PDF (all pages, including scanned/drawing pages).\n"
        "Look for labels like furncloud, furnplan, planung, plan, code, id and nearby bracket/parenthesis tokens.\n"
        "Accepted pattern: 8 alphanumeric characters total (with optional separator, e.g. 'yif3 aqz7').\n"
        "If a valid furncloud_id is found once, apply the same furncloud_id to all items.\n"
        "If not found, leave furncloud_id empty.\n"
        "\n"
        "=== SEGMULLER ADDRESS RULES ===\n"
        "lieferanschrift: read from Lieferung an / Lieferanschrift block and output only:\n"
        "- line 1 = street + house number\n"
        "- line 2 = PLZ + city\n"
        "Drop recipient/company line from lieferanschrift.\n"
        "Do not include ILN/GLN lines in lieferanschrift.\n"
        "store_name: company entity from Auftragsbestaetigungsanschrift or Rechnungsanschrift block.\n"
        "store_address: only street + house number + PLZ/city lines from Auftragsbestaetigungsanschrift or Rechnungsanschrift block.\n"
        "Address examples:\n"
        "- lieferanschrift example: Am Rotboell 7\\n64331 Weiterstadt\n"
        "- store_address example: Muenchner Str. 35\\n86316 Friedberg\n"
        "\n"
        "=== SEGMULLER ILN MAPPING ===\n"
        "Delivery block ILN/GLN -> iln_anl and iln.\n"
        "Store/billing ILN from Auftragsbestaetigungsanschrift or Rechnungsanschrift -> iln_fil.\n"
        "Do not swap delivery/store ILN mappings.\n"
        "Do not place ILN text into address fields.\n"
        "\n"
        "=== HEADER EXTRACTION HINTS ===\n"
        "kundennummer: Kundennr/Kunden-Nr/Debitor/Konto\n"
        "kom_nr: Auftragsnr/Bestellnr/Order/Kommission\n"
        "kom_name: only the name part (example: '22300 NUESSLER' -> 'NUESSLER').\n"
        "bestelldatum: Bestelldatum/Datum\n"
        "liefertermin or wunschtermin: Liefertermin/Wunschliefertermin\n"
        "lieferanschrift: Lieferadresse/Lieferanschrift/Empfaenger block\n"
        "ILN from Anlieferung block: If the 'Anlieferung' section contains a 13-digit ILN/GLN "
        "(often starting with 40 or 90), extract it into BOTH iln_anl and iln.\n"
        "Do NOT include that 13-digit ILN line inside lieferanschrift.\n"
        "GLN Haus / Fuer Haus is NOT the delivery ILN. Do NOT map GLN Haus to iln or iln_anl.\n"
        "If both GLN Haus and Anlieferung ILN appear, always use the Anlieferung number.\n"
        "Keep iln_fil empty unless explicitly present elsewhere.\n"
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        "Return strict JSON with top-level keys:\n"
        "message_id, received_at, header, items, status, warnings, errors\n"
        "status must be one of: ok, partial, failed.\n"
    )
