"""
Prompts for Braun order extraction (email + PDF).
"""

from __future__ import annotations


BRAUN_SYSTEM_PROMPT = (
    "You are a strict Braun purchase-order extraction engine. "
    "Extract one order from email + PDF into the required JSON schema. "
    "Return JSON only (no markdown, no commentary). "
    "Use only German field names exactly as requested."
)


def build_user_instructions_braun(source_priority: list[str]) -> str:
    return (
        "=== TASK ===\n"
        "Extract one Braun order from email + PDF pages.\n"
        f"SOURCE TRUST PRIORITY: {', '.join(source_priority).upper()}\n"
        "When sources conflict, follow the priority above.\n"
        "NOTE: The email body is a generic template only — all order data lives in the PDF.\n"
        "\n"
        "=== REQUIRED KEYS (EXACT NAMES) ===\n"
        "Header keys:\n"
        "ticket_number, kundennummer, adressnummer, kom_nr, kom_name, "
        "liefertermin, wunschtermin, bestelldatum, lieferanschrift, tour, "
        "store_name, store_address, seller, iln, iln_anl, iln_fil, "
        "human_review_needed, reply_needed, post_case\n"
        "Item keys:\n"
        "artikelnummer, modellnummer, menge, furncloud_id\n"
        "No English aliases.\n"
        "\n"
        "=== FIELD OBJECT FORMAT ===\n"
        "Each header/item field must be an object:\n"
        '{"value":"...", "source":"pdf|email|image|derived", "confidence":0.0-1.0}\n'
        "Always include every required key, even if value is empty.\n"
        "\n"
        "=== PDF INPUT USAGE ===\n"
        "Each PDF page includes image + digital text.\n"
        "Use the IMAGE to determine table structure, number of rows, and item quantities (menge).\n"
        "Use digital PDF text only to confirm/correct code fields and OCR ambiguities:\n"
        "- items[*].modellnummer\n"
        "- items[*].artikelnummer\n"
        "Preserve exact characters, including leading zeros and O vs 0.\n"
        "\n"
        "=== ROW EXTRACTION ===\n"
        "Create one output item per explicit order row in reading order.\n"
        "Assign line_no sequentially starting at 1.\n"
        "Do not reorder rows.\n"
        "\n"
        "=== BRAUN AUFTRAGS-NR PARSING (kom_nr + kom_name + seller) ===\n"
        "The 'unsere Auftrags-Nr' line has the format:\n"
        "  [HYPHENATED-NUMBER]  [Lastname*Firstname]\n"
        "Examples:\n"
        "  '21-305051-12  Sauter*Reinhard'  -> kom_nr='21-305051-12', kom_name='Sauter*Reinhard'\n"
        "  '11-658206-12  Reisch*Wolfgang'  -> kom_nr='11-658206-12', kom_name='Reisch*Wolfgang'\n"
        "  '11-660605-12  Schweizer*Frank'  -> kom_nr='11-660605-12', kom_name='Schweizer*Frank'\n"
        "Rules:\n"
        "- kom_nr  = the hyphenated number before the space (e.g., '21-305051-12')\n"
        "- kom_name = the full Lastname*Firstname token after the space (e.g., 'Sauter*Reinhard')\n"
        "- seller  = same value as kom_name (no separate 'Verkaefer:' label appears in Braun orders)\n"
        "- The asterisk in kom_name/seller is a separator — preserve it exactly as-is.\n"
        "\n"
        "=== BRAUN STORE & DELIVERY ADDRESS ===\n"
        "\n"
        "store_name and store_address (from letterhead):\n"
        "- The top-left of the letterhead contains a 'HAUS [CITY]' location identifier.\n"
        "- Combine it with 'BRAUN Moebel-Center' for the full store name.\n"
        "- Examples:\n"
        "    'HAUS SINGEN'     -> store_name = 'BRAUN Moebel-Center HAUS SINGEN'\n"
        "    'HAUS REUTLINGEN' -> store_name = 'BRAUN Moebel-Center HAUS REUTLINGEN'\n"
        "- store_address = the address shown top-right of the letterhead (next to HAUS name).\n"
        "  Examples: 'Carl-Benz-Strasse 22\\n78224 Singen'\n"
        "            'Markwiesenstr. 38\\n72770 Reutlingen'\n"
        "\n"
        "lieferanschrift (delivery address — CRITICAL):\n"
        "- Braun PDFs use one of two delivery block labels:\n"
        "    Format 1: 'Auftragsbestaetigung, Lieferung und Rechnung an unser Haus:'\n"
        "    Format 2: 'ANLIEFERUNG an unser Haus:'\n"
        "- Both signal the start of the delivery address. Extract the address lines that follow.\n"
        "- Include: company name, street + number, postal code + city.\n"
        "- Exclude: Telefon and Email lines (informational only).\n"
        "- IMPORTANT: The delivery street number may differ from the letterhead address.\n"
        "  Always use the address in the delivery block, NOT the letterhead address.\n"
        "  Example: letterhead shows 'Markwiesenstr. 38' but delivery block says 'Markwiesenstr. 37'.\n"
        "  Use 'Markwiesenstr. 37' for lieferanschrift.\n"
        "\n"
        "=== BRAUN ITEM EXTRACTION (CRITICAL) ===\n"
        "Braun PDFs identify articles via one of four code formats.\n"
        "Check for each format in the PRIORITY ORDER listed below.\n"
        "Use the FIRST matching format found for that position.\n"
        "\n"
        "RIGHT-ALIGNED BRAUN REFERENCE NUMBER (applies to ALL formats):\n"
        "  Every item block has a right-aligned number (e.g., 176472, 837193, 791155).\n"
        "  This is a Braun-internal position/catalog reference only.\n"
        "  It does NOT map to any output field — ignore it for artikelnummer, modellnummer,\n"
        "  and furncloud_id alike.\n"
        "\n"
        "furncloud_id RULE (applies to ALL formats):\n"
        "  Braun orders do NOT contain Furncloud IDs.\n"
        "  furncloud_id is ALWAYS empty string '' for every Braun item.\n"
        "  Do NOT put the right-aligned Braun reference number in furncloud_id.\n"
        "\n"
        "modellnummer RULE (applies to ALL formats):\n"
        "  modellnummer MUST come from an explicit code field (Art.Nr. or similar).\n"
        "  NEVER put a product/series name (e.g., 'System One', 'Kombikommode') in modellnummer.\n"
        "  If no code-based modellnummer is available, leave modellnummer as empty string.\n"
        "\n"
        "--- FORMAT D (HIGHEST PRIORITY) — 'Art.Nr.: MODEL-ARTICLE' ---\n"
        "  Trigger: An 'Art.Nr.:' line is present anywhere in the item block.\n"
        "  Split the code on the hyphen:\n"
        "  - modellnummer  = part BEFORE the hyphen (e.g., 'CQ961699')\n"
        "  - artikelnummer = part AFTER  the hyphen (e.g., '72118C')\n"
        "  - menge         = quantity from the main position line\n"
        "  - furncloud_id  = '' (empty — Braun does not use Furncloud)\n"
        "  - Create ONE output item.\n"
        "  Example from PDF:\n"
        "    '1 Kombikommode System One'  (right-aligned: 176472 — ignore)\n"
        "    'Korpus: Dekor Artisan Eiche/ Front Dekor Weiss/'\n"
        "    'Art.Nr.: CQ961699-72118C'\n"
        "    -> modellnummer='CQ961699', artikelnummer='72118C', menge=1, furncloud_id=''\n"
        "\n"
        "--- FORMAT A — Multiple sub-items: '[N]x Typ NNNNN' lines ---\n"
        "  Trigger: One or more lines matching '[N]x Typ [CODE]' under the position.\n"
        "  Each such line is ONE separate output item.\n"
        "  - artikelnummer = the code immediately after 'Typ' (e.g., '60948', '14328')\n"
        "  - menge         = the integer before 'x Typ' (e.g., '1x Typ ...' -> menge=1)\n"
        "  - modellnummer  = empty string\n"
        "  - furncloud_id  = '' (empty)\n"
        "  - Create one output item PER '[N]x Typ' line. Do NOT collapse into one item.\n"
        "  Example from PDF:\n"
        "    '1 Schrank System One 01-29'  (right-aligned: 837193 — ignore)\n"
        "    '1x Typ 60948 B/H/T 100/240/63 cm'  -> line_no=1, artikelnummer='60948', menge=1\n"
        "    '1x Typ 64850 B/H/T 100/240/63 cm'  -> line_no=2, artikelnummer='64850', menge=1\n"
        "    '1x Typ 61347 B/H/T 100/240/63 cm'  -> line_no=3, artikelnummer='61347', menge=1\n"
        "    '1x Typ 61494 Passepartoutrahmen ...'-> line_no=4, artikelnummer='61494', menge=1\n"
        "    '1x Typ 14328 Einlegeboden ...'      -> line_no=5, artikelnummer='14328', menge=1\n"
        "    All 5 items: modellnummer='', furncloud_id=''\n"
        "\n"
        "--- FORMAT B — Single item: 'Typ: NNNNN' (colon separator) ---\n"
        "  Trigger: A 'Typ: [CODE]' line (with colon) present, no Art.Nr. line.\n"
        "  - artikelnummer = code after 'Typ:' (may include letters, e.g., '70594G')\n"
        "  - menge         = quantity from the main position line\n"
        "  - modellnummer  = empty string\n"
        "  - furncloud_id  = '' (empty)\n"
        "  - Create ONE output item.\n"
        "  Example from PDF:\n"
        "    '1 Schreibtisch System One'  (right-aligned: 791155 — ignore)\n"
        "    'Ausf. Dekor weiss, CQ9696'\n"
        "    'Typ: 70594G B/H/T:145x72x68cm'\n"
        "    -> artikelnummer='70594G', menge=1, modellnummer='', furncloud_id=''\n"
        "\n"
        "--- FORMAT C — No code line at all ---\n"
        "  Trigger: No Art.Nr., no '[N]x Typ', no 'Typ:' line under the position.\n"
        "  - artikelnummer = right-aligned Braun reference number (only available identifier)\n"
        "  - menge         = quantity from the main position line\n"
        "  - modellnummer  = empty string\n"
        "  - furncloud_id  = '' (empty)\n"
        "  - Create ONE output item.\n"
        "  Example from PDF:\n"
        "    '1 Schwebetuerenschrank System One 41-49'  (right-aligned: 879878)\n"
        "    '3x Fachboeden'\n"
        "    '1x T-Einteilung'\n"
        "    -> artikelnummer='879878', menge=1, modellnummer='', furncloud_id=''\n"
        "\n"
        "ACCESSORY LINES (NOT separate items):\n"
        "  Lines starting with '[N]x [descriptor]' that do NOT contain 'Typ' are product\n"
        "  attributes / included accessories — NOT separate order items.\n"
        "  Examples: '3x Fachboeden', '1x T-Einteilung', '1x Schubkaseneinsatz, 2 Schubkasten'\n"
        "  DO NOT create output items for these lines.\n"
        "\n"
        "COLOR/FINISH CODES (NOT artikelnummer or modellnummer):\n"
        "  Codes on 'Ausf.' / 'Korpus:' / 'Front:' lines are finish/color designators.\n"
        "  Examples: 'CQ9696' in 'Ausf. Dekor weiss, CQ9696'\n"
        "  DO NOT map these to artikelnummer or modellnummer.\n"
        "  Only codes on an explicit 'Art.Nr.:' or 'Typ' line are article identifiers.\n"
        "\n"
        "=== BRAUN FIELD SPECIFICS ===\n"
        "\n"
        "kundennummer:\n"
        "  From 'Kunden-Nr.' in the top-left letterhead area.\n"
        "  Example: 'Kunden-Nr. 28473' -> kundennummer='28473'\n"
        "\n"
        "bestelldatum:\n"
        "  From 'Datum' field. Format: DD.MM.YYYY. Preserve as-is.\n"
        "\n"
        "wunschtermin and liefertermin:\n"
        "  'Gewuenschter Liefertermin: XX. Woche YYYY' -> wunschtermin='XX. Woche YYYY'\n"
        "  Preserve the week notation exactly (e.g., '05. Woche 2026', '10. Woche 2026').\n"
        "  Do NOT convert to a calendar date.\n"
        "  If no separate liefertermin field is found, set liefertermin = wunschtermin value.\n"
        "\n"
        "ILN fields (iln, iln_anl, iln_fil):\n"
        "  Braun orders do NOT contain ILN/GLN numbers.\n"
        "  Leave iln, iln_anl, iln_fil as empty strings unless a 13-digit number is\n"
        "  explicitly visible in the document.\n"
        "  Do NOT invent or hallucinate ILN values.\n"
        "\n"
        "furncloud_id:\n"
        "  Braun orders do NOT use Furncloud IDs (no '[xxxx xxxx]' bracket codes exist).\n"
        "  furncloud_id is ALWAYS empty string '' for every item in every Braun order.\n"
        "  The right-aligned Braun position reference number is a Braun-internal reference\n"
        "  and must NOT be placed in furncloud_id.\n"
        "\n"
        "tour, adressnummer, ticket_number:\n"
        "  These are typically absent from Braun orders. Leave as empty strings.\n"
        "\n"
        "human_review_needed:\n"
        "  Set to true if artikelnummer is empty for any item (Format C with no right-aligned\n"
        "  reference number), or if any field confidence is below 0.6.\n"
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        "Return strict JSON with top-level keys:\n"
        "message_id, received_at, header, items, status, warnings, errors\n"
        "status must be one of: ok, partial, failed.\n"
    )
