"""
Prompts for Porta order extraction (email + PDF).
"""

from __future__ import annotations


PORTA_SYSTEM_PROMPT = (
    "You are a strict Porta purchase-order extraction engine. "
    "Extract one order from email + PDF into the required JSON schema. "
    "Return JSON only (no markdown, no commentary). "
    "Use only German field names exactly as requested."
)


def build_user_instructions_porta(source_priority: list[str]) -> str:
    return (
        "=== TASK ===\n"
        "Extract one Porta order from email + PDF pages.\n"
        f"SOURCE TRUST PRIORITY: {', '.join(source_priority).upper()}\n"
        "When sources conflict, follow the priority above.\n"
        "\n"
        "=== REQUIRED KEYS (EXACT NAMES) ===\n"
        "Header keys:\n"
        "ticket_number, kundennummer, adressnummer, kom_nr, kom_name, "
        "liefertermin, wunschtermin, bestelldatum, lieferanschrift, tour, "
        "store_name, store_address, seller, iln, iln_anl, iln_fil, mail_to, "
        "human_review_needed, reply_needed, post_case\n"
        "Item keys:\n"
        "artikelnummer, modellnummer, menge, furncloud_id\n"
        "No English aliases.\n"
        "\n"
        "=== FIELD OBJECT FORMAT ===\n"
        "Each header/item field must be an object:\n"
        '{"value":"...", "source":"pdf|email|image|derived", "confidence":0.0-1.0}\n'
        "Always include every required key, even if value is empty.\n"
        "\n"
        "=== ARTIKELNUMMER FORMAT (HARD CONSTRAINT) ===\n"
        "artikelnummer is ALWAYS a 5-digit number, optionally followed by a single letter (e.g., '72216', '76947G').\n"
        "A token with fewer than 5 digits (e.g., '5222', '123') is NEVER a valid artikelnummer.\n"
        "A purely alphabetic token or a short alphanumeric token (e.g., '93AR') is NEVER a valid artikelnummer.\n"
        "If no valid 5-digit artikelnummer exists in an item block, set artikelnummer to empty string.\n"
        "\n"
        "=== SIEHE PLANUNG — FURNCLOUD ONLY (HARD CONSTRAINT) ===\n"
        "Any phrase matching 'Siehe Planung(...)' or 'Siehe Planung (...)' contains ONLY a furncloud_id.\n"
        "The tokens inside the parentheses are the furncloud code — they are NOT an artikelnummer, NOT a modellnummer, "
        "and must NOT trigger creation of a new item row. Ever.\n"
        "Consuming a 'Siehe Planung' phrase as furncloud_id EXHAUSTS that text. "
        "Do not re-process it under any item-code rule.\n"
        "\n"
        "=== PORTA ITEM-CODE RULES (STRICT) ===\n"
        "Apply these mappings exactly for Porta style codes:\n"
        "0) Ignore ANY PDF table 'Artikel-Nr' value (often like '4609952 / 88' or '1005141 / 88'). "
        "This is a store-internal number and must NEVER be used as artikelnummer or modellnummer. "
        "Do NOT split it, normalize it, or use it as a fallback.\n"
        "   Example (NEGATIVE): Artikel-Nr: 1005141 / 88 -> IGNORE ENTIRELY\n"
        "0a) Hard code-shape validation for Porta item codes:\n"
        "   - modellnummer must be code-like: uppercase alphanumeric token containing at least one letter and at least one digit.\n"
        "     Pure descriptor words (e.g., SONATE) are NEVER modellnummer.\n"
        "   - artikelnummer must contain exactly 5 digits, optionally plus exactly 1 letter anywhere in the token.\n"
        "     Valid examples: '56789', '56789A', 'A56789', '56A789'.\n"
        "     4-digit numbers like '4008' are NEVER artikelnummer.\n"
        "0b) Explicit labeled item-code fields take precedence over generic description splitting:\n"
        "   If the same item block contains explicit labels like 'ArtNr'/'Art.Nr.' and "
        "'Modell-Nr'/'Model-Nr', treat these labeled values as authoritative item codes.\n"
        "   - Map ArtNr/Art.Nr numeric token -> artikelnummer\n"
        "   - Map Modell-Nr/Model-Nr token -> modellnummer\n"
        "   - Do NOT discard these labeled pairs because of generic fallback validity gates.\n"
        "   - These explicit labeled pairs override generic Liefermodell descriptor splitting.\n"
        "0c) Anti-misclassification for Liefermodell descriptor text:\n"
        "   A plain descriptor + number phrase such as 'Liefermodell: Sonate 4008' is NOT a valid "
        "modellnummer/artikelnummer pair (including when no explicit ArtNr/Modell-Nr labels are present).\n"
        "   Do NOT output furniture-name descriptor words (e.g., 'SONATE') as modellnummer unless "
        "the token is explicitly label-bound as model code or clearly code-like.\n"
        "   NEGATIVE EXAMPLE: 'Liefermodell: Sonate 4008' -> NOT modellnummer='SONATE', artikelnummer='4008'\n"
        "   If no valid code pair exists after applying all Porta rules, keep the row quantity but set "
        "modellnummer='' and artikelnummer=''.\n"
        "0d) Multiple explicit Modell-Nr values in one item block:\n"
        "   If one explicit ArtNr is paired with multiple explicit Modell-Nr/Model-Nr values, "
        "create one output item per explicit Modell-Nr in reading order.\n"
        "   Reuse the same artikelnummer for each such line.\n"
        "   Quantity defaults to the parent row quantity unless a sub-line quantity is explicitly shown.\n"
        "   POSITIVE EXAMPLE: 'ArtNr: 72797' + 'Modell-Nr. OPGPZB2020' + 'Model-Nr: OGPG00' ->\n"
        "   line A: artikelnummer='72797', modellnummer='OPGPZB2020'\n"
        "   line B: artikelnummer='72797', modellnummer='OGPG00'\n"
        "   IMPORTANT: 'ArtNr' in a Furnplan/Furncloud planning document is a DIFFERENT column from the ignored "
        "'Artikel-Nr' table column. Furnplan 'ArtNr' values like 'CQ9696TB-56121' or 'OJ99-12737' are VALID "
        "and must be processed by the normal item-code rules (rules 1–10 above).\n"
        "1) Combined 'Ausführung' + 'Art.Nr.' pair inside the same item block:\n"
        "   Example: 'Ausführung: 78706' and 'Art.Nr. PD967136SP96'\n"
        "   -> artikelnummer='78706'\n"
        "   -> modellnummer='PD967136SP96'\n"
        "   This pair takes precedence over generic fallback splitting rules.\n"
        "   IMPORTANT: this 'Art.Nr.' item-code label is different from the table-column 'Artikel-Nr.' and is valid.\n"
        "2) Main code pattern around 'Auf.' line:\n"
        "   Example: 'Auf. CQ 1616 TP-67430'\n"
        "   -> artikelnummer='67430'\n"
        "   -> modellnummer='CQ1616'\n"
        "   Never swap these two for the main 'Auf.' line; the CQ+digits is always modellnummer, "
        "   the TP-<digits> is always artikelnummer (strip the 'TP-' prefix).\n"
        "   WRONG: artikelnummer='CQ1616', modellnummer='67430'\n"
        "   CORRECT: artikelnummer='67430', modellnummer='CQ1616'\n"
        "2b) Typ/Ausf paired code lines in the same item block:\n"
        "   Example: 'Typ 77171' and 'Ausf. CQ1616'\n"
        "   -> artikelnummer='77171'\n"
        "   -> modellnummer='CQ1616'\n"
        "   'Typ' is an article label and is NEVER a modellnummer token.\n"
        "   This rule does NOT make table-column 'Artikel-Nr.' valid; keep table 'Artikel-Nr.' ignored.\n"
        "3) Accessory code pattern '<PREFIX>-<NUMERIC>' OR '<PREFIX> <NUMERIC>' where prefix starts with 0J or OJ:\n"
        "   -> modellnummer='<PREFIX>' (NO trailing dash)\n"
        "   -> artikelnummer='<NUMERIC>'\n"
        "   Examples:\n"
        "   - OJ99-14323 -> modellnummer='OJ99', artikelnummer='14323'\n"
        "   - OJ00-66017 -> modellnummer='OJ00', artikelnummer='66017'\n"
        "   - OJ00 31681 -> modellnummer='OJ00', artikelnummer='31681'\n"
        "   - 0J00-30156 -> modellnummer='0J00', artikelnummer='30156'\n"
        "   - 0J00-15237 -> modellnummer='0J00', artikelnummer='15237'\n"
        "   Fallback for OJ/0J prefix without visible numeric suffix:\n"
        "   If token starts with OJ or 0J but no '-<NUMERIC>' is visible (or no extractable numeric article token "
        "exists in that row), keep the row and quantity, set modellnummer to the prefix token and artikelnummer empty.\n"
        "   Example: OJ99 F-Einteilung Sockel 81 -> modellnummer='OJ99', artikelnummer=''\n"
        "4) Standard hyphen split (not 'Auf.' line and not 0J/OJ accessory pattern):\n"
        "   -> modellnummer=part BEFORE hyphen\n"
        "   -> artikelnummer=part AFTER hyphen\n"
        "   Example: CQ1616XP-00943 -> modellnummer='CQ1616XP', artikelnummer='00943'\n"
        "4b) Slash-separated component pair '<MODEL>/<NUMERIC>' is valid item code syntax\n"
        "   (different from the ignored table-column 'Artikel-Nr.').\n"
        "   -> modellnummer=part BEFORE slash\n"
        "   -> artikelnummer=part AFTER slash\n"
        "   Example: PD96713696/54415 -> modellnummer='PD96713696', artikelnummer='54415'\n"
        "5) Two adjacent code-like tokens in item description (not 'Auf.' line or 0J/OJ pattern):\n"
        "   If one token is a valid artikelnummer token (5 digits, optionally plus one letter anywhere),\n"
        "   -> artikelnummer=that token\n"
        "   -> modellnummer=the other token\n"
        "   Example: CQ1616 72216 -> modellnummer='CQ1616', artikelnummer='72216'\n"
        "5b) Spaced trailing single-letter suffix belongs to artikelnummer when directly attached to the same model/article occurrence:\n"
        "   Pattern: '<MODEL> <NUMERIC_ARTICLE> <SINGLE_LETTER_SUFFIX>'\n"
        "   -> artikelnummer='<NUMERIC_ARTICLE><SINGLE_LETTER_SUFFIX>' (remove only the separator space)\n"
        "   -> modellnummer='<MODEL>'\n"
        "   Example: CQEG9199 76912 C -> modellnummer='CQEG9199', artikelnummer='76912C'\n"
        "   See SIEHE PLANUNG constraint above — such phrases are fully excluded from this rule.\n"
        "6) If an item block contains the phrase 'bestehend aus je:', treat it as a decomposition block.\n"
        "   IGNORE the parent item row above the phrase for item extraction.\n"
        "   Extract only explicit component sub-lines after 'bestehend aus je:'.\n"
        "   If the same component pair appears multiple times in explicit sub-lines, output it multiple times.\n"
        "   Do NOT deduplicate identical component pairs across different pages.\n"
        "   A repeated occurrence on another page is a NEW item occurrence and must be output again.\n"
        "   Repeated PDF table 'Artikel-Nr.' values do not suppress item creation.\n"
        "   NEGATIVE EXAMPLE: legal/footer lines like 'Amtsgericht ... HRB 9684' are NEVER item/component pairs.\n"
        "   If a component line contains two code pairs, choose the pair that belongs to the component occurrence.\n"
        "7) Do not keep combined token in one field when it clearly splits.\n"
        "7b) If a model/article token starts with a quantity prefix (e.g., '1xPDSL71SP44-57383' or '2xCQ1212-09377G'), "
        "treat '<number>x' as quantity marker and strip it from modellnummer.\n"
        "8) Preserve leading zeros and uppercase letters exactly.\n"
        "9) Preserve O vs 0 exactly as seen (do not normalize).\n"
        "10) Standalone numeric tokens (e.g., '66015') and plus-joined numeric tokens (e.g., '30156+15237')\n"
        "   are NOT valid item-code rows unless an explicit model prefix is present in the same occurrence.\n"
        "   Do NOT infer a missing model prefix (for example, do not invent OJ/0J when it is not explicitly present).\n"
        "11) If no other valid code patterns or tokens exist in the item block (excluding the OJ/0J model-only fallback above), "
        "set artikelnummer.value and modellnummer.value to empty strings with source='derived' "
        "and confidence=0.0.\n"
        "\n"
        "=== PORTA ROW EXTRACTION ===\n"
        "Porta item blocks can contain a base line plus accessory lines (e.g., '1 x ... 0J00-30156').\n"
        "Create one output item per explicit code occurrence in reading order.\n"
        "\n"
        "MENGE RULES (CRITICAL - always read from the correct column):\n"
        "A) Top-level table rows (rows with a number in the far-left Menge column AND an Artikel-Nr value like '4624469 / 67'):\n"
        "   - If the row has NO 'bestehend aus je:' sub-list: the product code comes from the Liefermodell description.\n"
        "     The menge for that item is the number in the far-left Menge column of THAT row.\n"
        "     Example: '2  Stk  4624469 / 67  Liefermodell: Sinfonie Plus CQEG1299 76947G ...' -> menge=2\n"
        "     WRONG: reading sub-item quantities (1 Stk) from a different row and applying them here.\n"
        "   - If the row HAS 'bestehend aus je:': ignore the parent row; extract sub-items with their own quantities.\n"
        "B) Sub-items within 'bestehend aus je:': use the explicit quantity prefix on that sub-line (e.g., '1 Stk', '2 Stk').\n"
        "   Example: '2 Stk CQ12 86087 Aussenseite ...' -> menge=2\n"
        "C) Accessory lines (e.g., '1 x OJ00-30156'): use the '1 x' or 'N x' prefix as menge.\n"
        "D) Default to 1 ONLY when no quantity is explicitly visible for that specific row.\n"
        "\n"
        "Create items strictly in PDF reading order (Pos 1, 1.1, 1.2, ...). Do not reorder.\n"
        "Assign line_no sequentially starting at 1.\n"
        "\n"
        "=== PDF INPUT USAGE ===\n"
        "Each PDF page includes image + digital text.\n"
        "Use image for table structure and quantities.\n"
        "Use digital text to confirm/correct artikelnummer/modellnummer and OCR confusion.\n"
        "\n"
        "=== FURNCLOUD ID (ROBUST) ===\n"
        "Find furncloud_id anywhere in email or PDF (all pages, all orientations).\n"
        "Do NOT depend on one fixed phrase.\n"
        "Scan ALL pages, even image/drawing pages with no item table; furncloud may appear only there.\n"
        "Before final output, sweep each page in order: main body, then all margins/side strips.\n"
        "\n"
        "Accept these candidate forms:\n"
        "- [xxxx xxxx]\n"
        "- (xxxx xxxx)\n"
        "- xxxx xxxx (unbracketed) when clearly code-like\n"
        "- Unlabeled/no-prefix/no-bracket 'XXXX XXXX' alphanumeric pair in Porta description/article context.\n"
        "- 'Bestellung laut Anlage' context: accept trailing code on the same line OR on the immediate next line.\n"
        "  Example: 'Bestellung laut Anlage' followed by '4pkg 54cs' -> furncloud candidate.\n"
        "- Standalone unlabeled code-like token in Porta article/description/sketch context, e.g., 'muba 4nuh'.\n"
        "- 'Siehe Skizze vcrr kwkk' and 'Siehe Skizze: vcrr kwkk' style phrases; treat the trailing code token as a furncloud candidate.\n"
        "- Near labels/phrases such as furncloud, furnplan, planung, plan, zeichnung, code, id, "
        "or phrases like 'Siehe Planung (...)'.\n"
        "\n"
        "Orientation/layout handling:\n"
        "- Accept candidates in normal, vertical, rotated, or side-strip text (0/90/180/270 degrees).\n"
        "- If present only in page image (not digital text), still extract from image.\n"
        "\n"
        "Validation and normalization:\n"
        "- Valid furncloud_id is exactly 8 alphanumeric characters total.\n"
        "- Ignore spaces/punctuation/linebreaks while counting 8 chars.\n"
        "- Example validation: '4pkg 54cs' -> valid (8 alphanumeric after cleanup).\n"
        "- For 'Siehe Skizze ...' phrases, accept only when the extracted candidate is exactly 8 alphanumeric characters after cleanup.\n"
        "- Store format must be 'XXXX XXXX' (4 chars, space, 4 chars).\n"
        "- Example store format: keep '4pkg 54cs' as '4pkg 54cs' (4+space+4).\n"
        "- If source is contiguous 8 chars (e.g., 'abcd1234'), normalize to 'abcd 1234'.\n"
        "- Preserve O vs 0 exactly as seen; do not normalize characters.\n"
        "\n"
        "Reject likely non-furncloud values:\n"
        "- ILN/GLN (13-digit numbers), ticket/order numbers, artikelnummer/modellnummer tokens, dates.\n"
        "- Any candidate that is not exactly 8 alphanumeric characters after cleanup.\n"
        "\n"
        "Per-item furncloud_id assignment (check these triggers IN ORDER — stop at the first that applies):\n"
        "1) INLINE ITEM LABEL — check in this order:\n"
        "   a) MULTI-ID SPLIT: If a label like 'Furncloud-ID:', 'Furncloud ID:', or 'Furncloud:' is "
        "followed by two or more slash-separated valid 8-char codes (e.g. 'Furncloud-ID: mcum 6gr8 /rghy f46y'), "
        "create one separate item row per code. Each split item copies all other fields "
        "(artikelnummer, modellnummer, menge, description) from the original row and receives "
        "one of the codes as its furncloud_id. Do NOT keep the original unsplit row.\n"
        "   b) SINGLE-ID LABEL: If the label contains exactly one valid 8-char code, assign it "
        "to the item's own furncloud_id.\n"
        "   c) 'Siehe Planung (xxxx xxxx)', 'Siehe Planung(xxxx xxxx)', or 'Siehe Skizze xxxx xxxx' "
        "— assign the trailing code to the item's own furncloud_id.\n"
        "   Different items may have different furncloud_ids.\n"
        "2) POSITIONAL N:N MATCH: If there are exactly N items and exactly N valid furncloud candidates found "
        "in the document, and each candidate appears closest to (or inside the row of) a different item, "
        "assign them 1:1 by position/reading order (candidate 1 → item 1, candidate 2 → item 2, etc.).\n"
        "3) DOCUMENT-LEVEL FALLBACK (single candidate only): If there is exactly 1 candidate in the whole "
        "document, assign it to ALL items.\n"
        "4) If none of the above apply (e.g. ambiguous multiple candidates that cannot be mapped per-item), "
        "use candidate ranking to pick one and assign it to all items:\n"
        "   a) Candidate near explicit labels/phrases (furncloud/furnplan/planung/plan/zeichnung).\n"
        "   b) Bracketed or parenthesized candidate.\n"
        "   c) Margin/side-strip candidate.\n"
        "   d) First by page order, then reading order on page.\n"
        "If no candidate survives, leave furncloud_id empty with low confidence.\n"
        "\n"
        "=== HEADER EXTRACTION HINTS ===\n"
        "kundennummer: Kundennr/Kunden-Nr/Debitor/Konto\n"
        "store_name:\n"
        "- Extract from the 'Verkaufshaus' footer block when present.\n"
        "- Use the FULL legal company/branch string exactly as shown, including legal suffixes "
        "(e.g., 'GmbH & Co. KG').\n"
        "- Do NOT shorten to city-only branch labels such as 'Porta Moebel Frechen' when the legal line "
        "contains a longer form (e.g., 'Porta Moebel Handels GmbH & Co. KG Frechen').\n"
        "- If no Verkaufshaus legal name is visible, fallback to the best available store name.\n"
        "kom_nr: Auftragsnr/Bestellnr/Order/Kommission/KN/K.Nr. If kom_nr ends with '/0', drop the '/0' and keep only the number.\n"
        "kom_name: Extract from Kommission/Kommissionsname line in PDF.\n"
        "  - If line is 'Kommission: <number> <name>', split into kom_nr and kom_name.\n"
        "  - If line is 'Kommissionsname: <name>', kom_name = <name>.\n"
        "  - kom_name can be a person OR a branch name like 'Porta Möbel Bad Vilbel'.\n"
        "  - Do NOT confuse kom_name with address or seller lines.\n"
        "bestelldatum: Bestelldatum/Datum\n"
        "liefertermin or wunschtermin: Liefertermin/Wunschliefertermin\n"
        "lieferanschrift: Lieferadresse/Lieferanschrift/Empfaenger block\n"
        "ILN from Anlieferung block: If the 'Anlieferung' section contains a 13-digit ILN/GLN "
        "(often starting with 40 or 90), extract it into BOTH iln_anl and iln.\n"
        "Do NOT include that 13-digit ILN line inside lieferanschrift.\n"
        "GLN Haus / Für Haus is NOT the delivery ILN. Do NOT map GLN Haus to iln or iln_anl.\n"
        "If both GLN Haus and Anlieferung ILN appear, ALWAYS use the Anlieferung number.\n"
        "Keep iln_fil empty unless explicitly present elsewhere.\n"
        "mail_to: Extract from 'Fragen an:' line. Pattern: 'Fragen an: <Name> - <email>' → extract only the email part after the last dash/hyphen. "
        "Example: 'Fragen an: Müller - rueckfragen.sietzsch@porta.de' → mail_to = 'rueckfragen.sietzsch@porta.de'. "
        "If no 'Fragen an:' line, leave empty.\n"
        "\n"
        "\n"
        "=== ADDRESS FORMATTING (STORE + LIEFERANSCHRIFT) ===\n"
        "store_address must be exactly two lines:\n"
        "Line 1: StreetName HouseNumber,\n"
        "Line 2: PLZ City\n"
        "lieferanschrift:\n"
        "- Do NOT include company/entity/branch name lines from the delivery block.\n"
        "- Keep only delivery address lines: street line + PLZ/City line.\n"
        "store_address:\n"
        "- Primary source is the 'Verkaufshaus' footer block.\n"
        "- If the Verkaufshaus store address is missing, use lieferanschrift for store_address.\n"
        "- If an explicit Verkaufshaus store address is present, keep it and do not overwrite it with lieferanschrift.\n"
        "If a 5-digit German postal code appears, insert a newline before it and add a comma before the newline.\n"
        "Fallback: If output ends up on a single line, still insert a comma immediately before the 5-digit PLZ.\n"
        "If the postal code is stuck to the house number (token ends with 5 digits, e.g., '204103'),\n"
        "split it into house number + postal code (e.g., '204103' -> house '2', PLZ '04103').\n"
        "Preserve characters/casing and hyphen spacing exactly as seen; only add a single comma before the newline.\n"
        "Example: 'Alte Messe 204103 Leipzig' -> 'Alte Messe 2,\\n04103 Leipzig'.\n"
        "Example (lieferanschrift): '... Bakenweg 16 - 20 32457 Porta Westfalica' "
        "-> '... Bakenweg 16 - 20,\\n32457 Porta Westfalica'.\n"
        "Example (lieferanschrift with company name present in source):\n"
        "'FuG Handelsg. Ost mbH & Co.KG Delitzscher Str. 6 06188 Sietzsch' ->\n"
        "'Delitzscher Str. 6,\\n06188 Sietzsch'.\n"
        "Example (store_address): 'Friedrich-Ebert-Str. 10133332 Guetersloh' "
        "-> 'Friedrich-Ebert-Str. 101,\\n33332 Guetersloh'.\n"
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        "Return strict JSON with top-level keys:\n"
        "message_id, received_at, header, items, status, warnings, errors\n"
        "status must be one of: ok, partial, failed.\n"
    )
