"""
Prompts for Porta order extraction (email + PDF).
"""

from __future__ import annotations


PORTA_SYSTEM_PROMPT = (
    "You are a strict Porta purchase-order extraction engine. "
    "Extract one order from email + PDF into the required JSON schema. "
    "Return JSON only (no markdown, no commentary). "
    "Use only German field names exactly as requested."
)


def build_user_instructions_porta(source_priority: list[str]) -> str:
    return (
        "=== TASK ===\n"
        "Extract one Porta order from email + PDF pages.\n"
        f"SOURCE TRUST PRIORITY: {', '.join(source_priority).upper()}\n"
        "When sources conflict, follow the priority above.\n"
        "\n"
        "=== REQUIRED KEYS (EXACT NAMES) ===\n"
        "Header keys:\n"
        "ticket_number, kundennummer, adressnummer, kom_nr, kom_name, "
        "liefertermin, wunschtermin, bestelldatum, lieferanschrift, tour, "
        "store_name, store_address, seller, iln_anl, iln_fil, "
        "human_review_needed, reply_needed, post_case\n"
        "Item keys:\n"
        "artikelnummer, modellnummer, menge, furncloud_id\n"
        "No English aliases.\n"
        "\n"
        "=== FIELD OBJECT FORMAT ===\n"
        "Each header/item field must be an object:\n"
        '{"value":"...", "source":"pdf|email|image|derived", "confidence":0.0-1.0}\n'
        "Always include every required key, even if value is empty.\n"
        "\n"
        "=== PORTA ITEM-CODE RULES (STRICT) ===\n"
        "Apply these mappings exactly for Porta style codes:\n"
        "1) Main code pattern around 'Auf.' line:\n"
        "   Example: 'Auf. CQ 1616 TP-67430'\n"
        "   -> artikelnummer='CQ1616'\n"
        "   -> modellnummer='67430'\n"
        "2) Accessory code pattern '<PREFIX>-<NUMERIC>' where prefix starts with 0J:\n"
        "   -> modellnummer='<PREFIX>-'\n"
        "   -> artikelnummer='<NUMERIC>'\n"
        "   Examples:\n"
        "   - 0J99-14323 -> modellnummer='0J99-', artikelnummer='14323'\n"
        "   - 0J00-66017 -> modellnummer='0J00-', artikelnummer='66017'\n"
        "   - 0J00-30156 -> modellnummer='0J00-', artikelnummer='30156'\n"
        "   - 0J00-15237 -> modellnummer='0J00-', artikelnummer='15237'\n"
        "3) Do not keep combined token in one field when it clearly splits.\n"
        "4) Preserve leading zeros and uppercase letters exactly.\n"
        "\n"
        "=== PORTA ROW EXTRACTION ===\n"
        "Porta item blocks can contain a base line plus accessory lines (e.g., '1 x ... 0J00-30156').\n"
        "Create one output item per explicit code occurrence in reading order.\n"
        "Set menge from the visible quantity for that code (default to 1 when line explicitly says '1 x').\n"
        "Assign line_no sequentially starting at 1.\n"
        "\n"
        "=== PDF INPUT USAGE ===\n"
        "Each PDF page includes image + digital text.\n"
        "Use image for table structure and quantities.\n"
        "Use digital text to confirm/correct artikelnummer/modellnummer and OCR confusion.\n"
        "\n"
        "=== HEADER EXTRACTION HINTS ===\n"
        "kundennummer: Kundennr/Kunden-Nr/Debitor/Konto\n"
        "kom_nr: Auftragsnr/Bestellnr/Order/Kommission\n"
        "bestelldatum: Bestelldatum/Datum\n"
        "liefertermin or wunschtermin: Liefertermin/Wunschliefertermin\n"
        "lieferanschrift: Lieferadresse/Lieferanschrift/Empfaenger block\n"
        "\n"
        "=== OUTPUT CONTRACT ===\n"
        "Return strict JSON with top-level keys:\n"
        "message_id, received_at, header, items, status, warnings, errors\n"
        "status must be one of: ok, partial, failed.\n"
    )
