from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timedelta, timezone
import os
import random
import uuid

from dotenv import load_dotenv
import psycopg
from psycopg.rows import dict_row

from db import init_db
from extraction_branches import BRANCHES
import order_store


def _database_url() -> str:
    url = (os.getenv("DATABASE_URL") or "").strip()
    if not url:
        raise RuntimeError("DATABASE_URL is not configured")
    return url


def _pick_status(rng: random.Random) -> str:
    roll = rng.random()
    if roll < 0.72:
        return order_store.STATUS_OK
    if roll < 0.84:
        return order_store.STATUS_REPLY
    if roll < 0.93:
        return order_store.STATUS_HUMAN
    if roll < 0.98:
        return order_store.STATUS_POST
    return order_store.STATUS_FAILED


def _random_received_at(rng: random.Random, days_back: int) -> datetime:
    now = datetime.now(timezone.utc)
    minutes_back = rng.randint(0, max(1, days_back * 24 * 60))
    return now - timedelta(minutes=minutes_back)


def _build_payload(
    *,
    idx: int,
    branch: str,
    status: str,
    received_at: datetime,
    rng: random.Random,
) -> tuple[dict, str | None]:
    client_no = (idx % 700) + 1
    item_count = 0 if status == order_store.STATUS_FAILED else rng.randint(1, 6)
    if status != order_store.STATUS_FAILED and rng.random() < 0.08:
        item_count = rng.randint(7, 14)

    items = []
    for line_no in range(1, item_count + 1):
        items.append(
            {
                "line_no": line_no,
                "artikelnummer": f"ART-{branch[:3].upper()}-{rng.randint(10000, 99999)}",
                "modellnummer": f"MOD-{rng.randint(1000, 9999)}",
                "menge": round(rng.uniform(1, 12), 3),
                "furncloud_id": f"FC-{rng.randint(100000, 999999)}",
            }
        )

    warnings: list[str] = []
    errors: list[str] = []
    parse_error: str | None = None

    if status in {order_store.STATUS_REPLY, order_store.STATUS_HUMAN, order_store.STATUS_POST}:
        warnings.append("Synthetic workflow flag set for performance seed")
    if status == order_store.STATUS_FAILED:
        errors.append("Synthetic parse failure generated by performance seed")
        parse_error = "Synthetic parse failure"

    header = {
        "ticket_number": f"T{received_at:%y%m}{idx:06d}",
        "kundennummer": f"K{client_no:05d}",
        "kom_nr": f"KOM-{client_no:04d}",
        "kom_name": f"Test Client {client_no:04d}",
        "liefertermin": (received_at + timedelta(days=rng.randint(1, 14))).date().isoformat(),
        "wunschtermin": (received_at + timedelta(days=rng.randint(2, 30))).date().isoformat(),
        "delivery_week": f"W{received_at.isocalendar().week:02d}",
        "store_name": f"Store {branch.upper()} {rng.randint(1, 25):02d}",
        "store_address": f"{rng.randint(10, 999)} Teststrasse, {rng.randint(1000, 9999)} City",
        "iln": str(9000000000000 + rng.randint(0, 999999999)),
        "reply_needed": status == order_store.STATUS_REPLY,
        "human_review_needed": status == order_store.STATUS_HUMAN,
        "post_case": status == order_store.STATUS_POST,
    }

    payload = {
        "message_id": f"seed-{uuid.uuid4()}",
        "received_at": received_at.isoformat(),
        "status": status,
        "header": header,
        "items": items,
        "warnings": warnings,
        "errors": errors,
        "extraction_branch": branch,
    }
    return payload, parse_error


def seed_dummy_orders(*, count: int, days_back: int, batch_size: int, seed: int) -> int:
    load_dotenv()
    init_db()

    branches = list(BRANCHES.keys())
    if not branches:
        raise RuntimeError("No extraction branches configured")

    rng = random.Random(seed)
    run_id = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    created_by_branch: Counter[str] = Counter()
    created_by_status: Counter[str] = Counter()

    with psycopg.connect(_database_url(), row_factory=dict_row, autocommit=False) as conn:
        for idx in range(count):
            branch = branches[idx % len(branches)]
            status = _pick_status(rng)
            received_at = _random_received_at(rng, days_back)
            payload, parse_error = _build_payload(
                idx=idx,
                branch=branch,
                status=status,
                received_at=received_at,
                rng=rng,
            )
            normalized = order_store._normalize_payload(payload)
            external_message_id = f"perf-seed-{run_id}-{idx:05d}-{uuid.uuid4().hex[:8]}"
            order_store._upsert_revision(
                conn,
                payload=normalized,
                external_message_id=external_message_id,
                change_type="ingested",
                changed_by_user_id=None,
                parse_error=parse_error,
                diff_json=None,
            )
            created_by_branch[branch] += 1
            created_by_status[status] += 1

            if (idx + 1) % batch_size == 0:
                conn.commit()
                print(f"Inserted {idx + 1}/{count} orders...")

        conn.commit()

    print("Seeding complete.")
    print("Branch distribution:")
    for branch in branches:
        print(f" - {branch}: {created_by_branch[branch]}")
    print("Status distribution:")
    for status in sorted(created_by_status):
        print(f" - {status}: {created_by_status[status]}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed synthetic orders for performance testing.")
    parser.add_argument("--count", type=int, default=20_000, help="Total number of orders to insert.")
    parser.add_argument("--days-back", type=int, default=180, help="Spread received_at over this many past days.")
    parser.add_argument("--batch-size", type=int, default=250, help="Commit after this many inserts.")
    parser.add_argument("--seed", type=int, default=20260305, help="Random seed for reproducible data.")
    args = parser.parse_args()

    if args.count < 1:
        raise SystemExit("--count must be >= 1")
    if args.days_back < 1:
        raise SystemExit("--days-back must be >= 1")
    if args.batch_size < 1:
        raise SystemExit("--batch-size must be >= 1")

    return seed_dummy_orders(
        count=args.count,
        days_back=args.days_back,
        batch_size=args.batch_size,
        seed=args.seed,
    )


if __name__ == "__main__":
    raise SystemExit(main())
